ums:
  jwt:
    issuer: localhost
    expiration: 86400000
    secret: B7CEFEB0F4E33DB6E2D661DF5615E6D33D3D2C6E05C504B49E4993762C20A75D
    refresh-expiration:
  admin:
    email: abc@email.com
    role: admin

server:
  port: 8501
spring:
  datasource:
    username: dev
    password: password
    url: jdbc:mysql://localhost:3306/ums-db
  jpa:
    hibernate:
      ddl-auto: validate